version: "3"
services:
  facial-recognition-s3:
    container_name: facial-recognition-s3
    image: minio/minio:RELEASE.2023-09-16T01-01-47Z
    environment:
      - MINIO_ACCESS_KEY=${S3_ACCESS_KEY}
      - MINIO_SECRET_KEY=${S3_SECRET_KEY}
    volumes:
      - ./s3-data:/s3-data
    command: minio server /s3-data --address :9000 --console-address :9001
    ports:
      - ${S3_API_PORT}:9000
      - ${S3_CONSOLE_PORT}:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - facial-recognition-network

  facial-recognition-s3-create-bucket:
    container_name: facial-recognition-s3-create-bucket
    image: minio/mc:RELEASE.2023-09-13T23-08-58Z
    environment:
    - MINIO_ACCESS_KEY=${S3_ACCESS_KEY}
    - MINIO_SECRET_KEY=${S3_SECRET_KEY}
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://facial-recognition-s3:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY};
      /usr/bin/mc mb --ignore-existing myminio/facial-recognition-bucket;
      exit 0;
      "
    depends_on:
      - facial-recognition-s3
    networks:
      - facial-recognition-network

  facial-recognition-es:
    image: elasticsearch:8.2.2
    container_name: facial-recognition-es
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.security.autoconfiguration.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    healthcheck:
      test: ["CMD", "curl", "localhost:9200"]
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    ports:
      - ${ES_API_PORT}:9200
    networks:
      - facial-recognition-network
  
  facial-recognition-es-create-index:
    container_name: facial-recognition-es-create-index
    image: curlimages/curl:8.3.0
    entrypoint: >
      curl -X PUT "facial-recognition-es:9200/${ES_INDEX}?pretty" -H 'Content-Type: application/json' -d' { "mappings": { "properties": { "embeddings": { "type": "dense_vector", "dims": ${ES_INDEX_EMBEDDINGS_DIMENSION}, "index": true, "similarity": "cosine" }, "name": { "type": "keyword" } } } } '
    depends_on:
      facial-recognition-es:
        condition: service_healthy
    networks:
      - facial-recognition-network

networks:
  facial-recognition-network:
    name: facial-recognition-network
